### ISSUE TITLE
[gnap] Request access (tx) API

### ISSUE THREAD

**Issue by Moopli** [trustbloc/auth#164]
GNAP [API](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-09.html#name-requesting-access).

When a client requests authorization, the auth server determines whether the client is currently authorized or if the client requires (re)authorization.
If the client requires (re)authorization, the auth server response contains at least the `interact` and `continue` fields:
- `interact`: provides the login&consent redirect URI, tokens for use there, etc
- `continue`: provides the URI for the followup auth request, which the client makes after completing the redirect login&consent.
If the client is authorized, the auth server response may contain the `access_token` and/or `subject` fields.

**Comment by rolsonquadras** [comment]
This has been implemented
